[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/nginx/supervisor-nginx.log
stderr_logfile=/var/log/nginx/supervisor-nginx-error.log
